language: node_js
node_js:
  - node

deploy:
  provider: npm
  email: xtrp@xtrp.io
  api_key:
    secure: GWzB+c8xzGQsIVBPKeSx7EK3vkrZC/2M6j/DdOmzvRA8KWj2zJKhGDyhZ5a6mk6L+AcnSVU6jY3KBDqh0aNNKPfa28NpVLsEMA0QLyMzgZBo8s9+E+GWR2eInP8PRNJCqVQLsE5N6+qbicZFkgwuQh4NimAkAUlCNjjQAKaIxW1PCuxevActbX8pMpBJxfNRv3IQKPhvg4pin5ziSr0h5EMAm6VQIEI9NFvrMerTehjSgkIqql4TNBNaS1WjmeUvpmHUJ10CS6GoyhSh8hTaC1CdQE1N65ob0VBCJGntlcV/eu02MZtGzJL3sJwvwCbCucNGPn1YN/DvZdfYWinQ+wgL+BES5IsjJSTn+weadD4L5WpYItwJBF7XO/VNExhD5nkKJxnXv0Ii5nA1xUI1A38wfqfOg8RY4SZajK6Xzx5JrqfEO0/6tLXzRwN1B6vSPD6azS+EZXYXDMR5ZvFvGYCeaHeLh+Y2w/i1HVIJAVXv9x8DLLQWFsh9cCGCGBN4zKAVRnlttSi3EN8GxpKExzLls9cTLFgcerPaa/kSaEougcQMk/1HGaQVUo+0vHYnD8MtzlmYZqb6Smc7WgOhXyAhLQViCWBtc5SqtYegqOVR6X91XbVNssXxPIKOFvxzL1uL1lxBCmoS6KR3//BBOv4MejbyAKf9T056RcI/oFU=
